from ...types import PyneFloat, PyneInt, PyneStr
from ...core.callable_module import CallableModule


class OpenTradesModule(CallableModule, int):
    def __call__(self) -> int: ...

    def new(self): ...

    #
    # Functions
    #

    def commission(self, trade_num: int) -> PyneFloat: ...

    def entry_bar_index(self, trade_num: int) -> PyneInt: ...

    def entry_comment(self, trade_num: int) -> PyneStr: ...

    def entry_id(self, trade_num: int) -> PyneStr: ...

    def entry_price(self, trade_num: int) -> PyneFloat: ...

    def entry_time(self, trade_num: int) -> PyneInt: ...

    def max_drawdown(self, trade_num: int) -> PyneFloat: ...

    def max_drawdown_percent(self, trade_num: int) -> PyneFloat: ...

    def max_runup(self, trade_num: int) -> PyneFloat: ...

    def max_runup_percent(self, trade_num: int) -> PyneFloat: ...

    def profit(self, trade_num: int) -> PyneFloat: ...

    def profit_percent(self, trade_num: int) -> PyneFloat: ...

    def size(self, trade_num: int) -> PyneFloat: ...


opentrades: OpenTradesModule = OpenTradesModule(__name__)
