from typing import Any, TypeVar, Generic, Type, Iterator

T = TypeVar('T')


class NA(Generic[T]):
    type: Type[T] | T | None

    def __new__(cls, type: Type[T] | T | None = int) -> NA[T]: ...
    def __init__(self, type: Type[T] | T | None = int) -> None: ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __round__(self, n: int = ...) -> Any: ...

    # Protocol compliance: SupportsFloat, SupportsIndex
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __index__(self) -> int: ...

    # Protocol compliance: Sized, Iterable
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __reversed__(self) -> Iterator[Any]: ...

    # Arithmetic — return Any so NA propagates without type conflicts
    def __neg__(self) -> Any: ...
    def __add__(self, _: Any) -> Any: ...
    def __radd__(self, _: Any) -> Any: ...
    def __sub__(self, _: Any) -> Any: ...
    def __rsub__(self, _: Any) -> Any: ...
    def __mul__(self, _: Any) -> Any: ...
    def __rmul__(self, _: Any) -> Any: ...
    def __truediv__(self, _: Any) -> Any: ...
    def __rtruediv__(self, _: Any) -> Any: ...
    def __mod__(self, _: Any) -> Any: ...
    def __rmod__(self, _: Any) -> Any: ...
    def __abs__(self) -> Any: ...

    # Bitwise
    def __and__(self, _: Any) -> Any: ...
    def __rand__(self, _: Any) -> Any: ...
    def __or__(self, _: Any) -> Any: ...
    def __ror__(self, _: Any) -> Any: ...
    def __xor__(self, _: Any) -> Any: ...
    def __rxor__(self, _: Any) -> Any: ...
    def __lshift__(self, _: Any) -> Any: ...
    def __rlshift__(self, _: Any) -> Any: ...
    def __rshift__(self, _: Any) -> Any: ...
    def __rrshift__(self, _: Any) -> Any: ...
    def __invert__(self) -> Any: ...

    # Comparison
    def __eq__(self, _: Any) -> bool: ...
    def __gt__(self, _: Any) -> bool: ...
    def __lt__(self, _: Any) -> bool: ...
    def __le__(self, _: Any) -> bool: ...
    def __ge__(self, _: Any) -> bool: ...

    # Catch-all for attribute access and indexing
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, _: Any) -> Any: ...
    def __call__(self, *_: Any, **__: Any) -> Any: ...


na_float: NA[float]
na_int: NA[int]
na_str: NA[str]
na_bool: NA[bool]