#@formatter:off
from __future__ import annotations
from typing import TypeVar, Generic, Any, Union, Protocol, TypeAlias
from .na import NA

T = TypeVar('T')

T_co = TypeVar('T_co', covariant=True)

class _SeriesIndexer(Protocol[T_co]):
    def __getitem__(self, index: int) -> T_co: ...

class _SeriesType(Generic[T_co], _SeriesIndexer[T_co]):
    """
    This is the runtime, do nothing implementation of the Series type. The actual Series behavior is
    implented in AST Transformers and the SeriesImpl class.
    """

    def __add__(self, other: Any) -> T_co: ...
    def __sub__(self, other: Any) -> T_co: ...
    def __mul__(self, other: Any) -> T_co: ...
    def __truediv__(self, other: Any) -> T_co: ...
    def __floordiv__(self, other: Any) -> T_co: ...
    def __mod__(self, other: Any) -> T_co: ...
    def __pow__(self, other: Any) -> T_co: ...

    def __radd__(self, other: Any) -> T_co: ...
    def __rsub__(self, other: Any) -> T_co: ...
    def __rmul__(self, other: Any) -> T_co: ...
    def __rtruediv__(self, other: Any) -> T_co: ...
    def __rfloordiv__(self, other: Any) -> T_co: ...
    def __rmod__(self, other: Any) -> T_co: ...
    def __rpow__(self, other: Any) -> T_co: ...

    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...

    def __abs__(self) -> T_co: ...
    def __neg__(self) -> T_co: ...
    def __pos__(self) -> T_co: ...
    def __round__(self, ndigits: int = 0) -> T_co: ...

    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# The type definition that allows both uses
Series: TypeAlias = Union[T_co, _SeriesType[T_co], NA[T_co]]
# The persistent version of the Series type
PersistentSeries: TypeAlias = Union[T_co, _SeriesType[T_co], NA[T_co]]
